name: Release on merge to main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Set up Node.js from .node-version
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build backend
        working-directory: backend
        run: yarn build

      - name: Package backend
        working-directory: backend
        run: yarn package

      - name: Bundle lambda
        working-directory: lambda
        run: yarn bundle

      - name: Check for Lambda updates
        id: lambda_change_check
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            lambda/**
            .github/**

      - name: Check for Backend updates
        id: backend_change_check
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            backend/**
            .github/**

      - name: Create GitHub Release
        if: steps.lambda_change_check.outputs.any_changed == 'true' || steps.backend_change_check.outputs.any_changed == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Release ${{ github.run_number }}"
          files: |
            lambda/dist/lambda.zip
            backend/dist/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        if: steps.backend_change_check.outputs.any_changed == 'true'
        working-directory: backend
        run: |
          npm publish --access public
